# Generated by Django 4.0.4 on 2022-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_ish', '0003_alter_student_options_student_holat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='holat',
            field=models.CharField(default="bahosi qo'yilmagan", max_length=100),
        ),
    ]
